### ISSUE TITLE
0.2.15 is missing from clojars

### ISSUE THREAD

**Issue by opqdonut** [bhauman/figwheel-core#6]
Looks like the release 0.2.15, required by figwheel-main 0.2.15, is missing from clojars.

Depending on `com.bhauman/figwheel-core {:mvn/version "0.2.15-SNAPSHOT"}` is a workaround.

PS. Thanks for fixing the goog logging breakage so quickly!

**Comment by bhauman** [comment]
Not sure what happened but I just pushed this out.

**Comment by opqdonut** [comment]
I see it now, thanks!
